export const QUESTIONS = [
    { id: 1, title: "Select all users", tags: ["SELECT", "COUNT"], difficulty: "Easy" },
    { id: 2, title: "Filter by Age", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 3, title: "Count Users by Age Group", tags: ["COUNT", "GROUP BY"], difficulty: "Medium" },
    { id: 4, title: "Find Youngest User", tags: ["SELECT", "ORDER BY", "LIMIT"], difficulty: "Easy" },
    { id: 5, title: "Second Highest Salary", tags: ["SELECT", "DISTINCT", "LIMIT", "OFFSET"], difficulty: "Medium" },
    { id: 6, title: "Duplicate Emails", tags: ["GROUP BY", "HAVING", "COUNT"], difficulty: "Easy" },
    { id: 7, title: "Employees Earning More Than Managers", tags: ["SELF JOIN", "WHERE"], difficulty: "Medium" },
    { id: 8, title: "Customers Who Never Order", tags: ["LEFT JOIN", "IS NULL"], difficulty: "Easy" },
    { id: 9, title: "Rising Temperature", tags: ["SELF JOIN", "DATE"], difficulty: "Easy" },
    { id: 10, title: "Rank Scores", tags: ["WINDOW FUNCTION", "DENSE_RANK"], difficulty: "Medium" },
    { id: 11, title: "Consecutive Numbers", tags: ["SELF JOIN"], difficulty: "Medium" },
    { id: 12, title: "Department Highest Salary", tags: ["JOIN", "GROUP BY", "SUBQUERY"], difficulty: "Medium" },
    { id: 13, title: "Delete Duplicate Emails", tags: ["DELETE", "SELF JOIN"], difficulty: "Easy" },
    { id: 14, title: "Exchange Seats", tags: ["CASE", "MOD"], difficulty: "Medium" },
    { id: 15, title: "Classes More Than 5 Students", tags: ["GROUP BY", "HAVING"], difficulty: "Easy" },
    { id: 16, title: "Combine Two Tables", tags: ["LEFT JOIN"], difficulty: "Easy" },
    { id: 17, title: "Nth Highest Salary", tags: ["LIMIT", "OFFSET", "DISTINCT"], difficulty: "Hard" },
    { id: 18, title: "Department Top 3 Salaries", tags: ["WINDOW", "DENSE_RANK"], difficulty: "Hard" },
    { id: 19, title: "Trips and Users", tags: ["JOIN", "CASE", "GROUP BY"], difficulty: "Hard" },
    { id: 20, title: "Human Traffic of Stadium", tags: ["SELF JOIN"], difficulty: "Hard" },
    { id: 21, title: "Tree Node", tags: ["CASE", "SUBQUERY"], difficulty: "Medium" },
    { id: 22, title: "Employees With Missing Info", tags: ["UNION", "IS NULL"], difficulty: "Easy" },
    { id: 23, title: "Rearrange Products Table", tags: ["UNION ALL"], difficulty: "Easy" },
    { id: 24, title: "Product Sales Analysis", tags: ["JOIN", "MIN"], difficulty: "Easy" },
    { id: 25, title: "Game Analysis I", tags: ["MIN", "GROUP BY"], difficulty: "Easy" },
    { id: 26, title: "Game Analysis II", tags: ["SUBQUERY"], difficulty: "Easy" },
    { id: 27, title: "Game Analysis III", tags: ["WINDOW", "SUM"], difficulty: "Medium" },
    { id: 28, title: "Employee Bonus", tags: ["LEFT JOIN"], difficulty: "Easy" },
    { id: 29, title: "Find Customer Referee", tags: ["WHERE", "IS NULL"], difficulty: "Easy" },
    { id: 30, title: "Customer Placing Largest Orders", tags: ["ORDER BY", "LIMIT"], difficulty: "Easy" },
    { id: 31, title: "Big Countries", tags: ["WHERE", "OR"], difficulty: "Easy" },
    { id: 32, title: "Article Views I", tags: ["WHERE", "DISTINCT"], difficulty: "Easy" },
    { id: 33, title: "Reformat Department Table", tags: ["CASE", "GROUP BY"], difficulty: "Easy" },
    { id: 34, title: "Monthly Transactions I", tags: ["GROUP BY", "SUM", "CASE"], difficulty: "Medium" },
    { id: 35, title: "Last Person to Fit in Bus", tags: ["WINDOW", "SUM"], difficulty: "Medium" },
    { id: 36, title: "Count Salary Categories", tags: ["CASE", "UNION"], difficulty: "Medium" },
    { id: 37, title: "Employees Whose Manager Left", tags: ["LEFT JOIN", "IS NULL"], difficulty: "Easy" },
    { id: 38, title: "Primary Department for Each Employee", tags: ["SUBQUERY", "UNION"], difficulty: "Easy" },
    { id: 39, title: "Fix Names in a Table", tags: ["SUBSTR", "UPPER", "LOWER"], difficulty: "Easy" },
    { id: 40, title: "Group Sold Products By The Date", tags: ["GROUP BY", "GROUP_CONCAT"], difficulty: "Easy" },
    { id: 41, title: "Patients With a Condition", tags: ["LIKE"], difficulty: "Easy" },
    { id: 42, title: "Second Highest Salary Different", tags: ["MAX", "SUBQUERY"], difficulty: "Medium" },
    { id: 43, title: "Find Followers Count", tags: ["GROUP BY", "COUNT"], difficulty: "Easy" },
    { id: 44, title: "Biggest Single Number", tags: ["GROUP BY", "HAVING", "MAX"], difficulty: "Easy" },
    { id: 45, title: "Not Boring Movies", tags: ["WHERE", "MOD", "ORDER BY"], difficulty: "Easy" },
    { id: 46, title: "Average Selling Price", tags: ["JOIN", "SUM", "AVG"], difficulty: "Easy" },
    { id: 47, title: "Project Employees I", tags: ["JOIN", "AVG"], difficulty: "Easy" },
    { id: 48, title: "Sales Analysis III", tags: ["GROUP BY", "HAVING"], difficulty: "Easy" },
    { id: 49, title: "Top Travelers", tags: ["LEFT JOIN", "GROUP BY", "ORDER BY"], difficulty: "Medium" },
    { id: 50, title: "Users That Actively Request Confirm", tags: ["HAVING", "AVG"], difficulty: "Easy" },
    { id: 51, title: "User Activity for Past 30 Days", tags: ["WHERE", "GROUP BY", "COUNT"], difficulty: "Easy" },
    { id: 52, title: "Product Price at a Given Date", tags: ["SUBQUERY", "COALESCE"], difficulty: "Medium" },
    { id: 53, title: "Immediate Food Delivery", tags: ["CASE", "AVG"], difficulty: "Medium" },
]
