export const QUESTIONS = [
    { id: 1, title: "Select All Users", tags: ["SELECT"], difficulty: "Easy" },
    { id: 2, title: "Filter Users by Age", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 3, title: "Count Users by City", tags: ["COUNT", "GROUP BY"], difficulty: "Medium" },
    { id: 4, title: "Find Youngest User", tags: ["SELECT", "ORDER BY", "LIMIT"], difficulty: "Easy" },
    { id: 5, title: "Second Highest Salary", tags: ["SELECT", "SUBQUERY", "MAX"], difficulty: "Medium" },
    { id: 6, title: "Duplicate Emails", tags: ["GROUP BY", "HAVING", "COUNT"], difficulty: "Easy" },
    { id: 7, title: "Employees Earning More Than Managers", tags: ["SELF JOIN"], difficulty: "Medium" },
    { id: 8, title: "Customers Who Never Order", tags: ["LEFT JOIN", "IS NULL"], difficulty: "Easy" },
    { id: 9, title: "Rising Temperature", tags: ["SELF JOIN", "DATE"], difficulty: "Medium" },
    { id: 10, title: "Rank Scores", tags: ["WINDOW FUNCTION", "DENSE_RANK"], difficulty: "Medium" },
    { id: 11, title: "Consecutive Numbers", tags: ["SELF JOIN"], difficulty: "Medium" },
    { id: 12, title: "Department Highest Salary", tags: ["JOIN", "SUBQUERY", "GROUP BY"], difficulty: "Medium" },
    { id: 13, title: "Exchange Seats", tags: ["CASE", "MOD"], difficulty: "Medium" },
    { id: 14, title: "Classes With 5+ Students", tags: ["GROUP BY", "HAVING"], difficulty: "Easy" },
    { id: 15, title: "Combine Two Tables", tags: ["LEFT JOIN"], difficulty: "Easy" },
    { id: 16, title: "Average Order Value", tags: ["AVG", "JOIN"], difficulty: "Easy" },
    { id: 17, title: "Products Never Sold", tags: ["LEFT JOIN", "IS NULL"], difficulty: "Easy" },
    { id: 18, title: "Top Selling Products", tags: ["JOIN", "GROUP BY", "ORDER BY", "LIMIT"], difficulty: "Medium" },
    { id: 19, title: "User Login Streak", tags: ["WINDOW FUNCTION"], difficulty: "Hard" },
    { id: 20, title: "Monthly Revenue", tags: ["GROUP BY", "SUM", "strftime"], difficulty: "Medium" },
    { id: 21, title: "Active Users", tags: ["COUNT", "DISTINCT", "WHERE"], difficulty: "Easy" },
    { id: 22, title: "Employee Hierarchy", tags: ["SELF JOIN", "RECURSIVE"], difficulty: "Hard" },
    { id: 23, title: "Order Status Summary", tags: ["CASE", "GROUP BY", "COUNT"], difficulty: "Medium" },
    { id: 24, title: "Running Total", tags: ["WINDOW FUNCTION", "SUM"], difficulty: "Medium" },
    { id: 25, title: "Nth Order Per Customer", tags: ["WINDOW FUNCTION", "ROW_NUMBER"], difficulty: "Hard" },
    { id: 26, title: "Query Challenge 26", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 27, title: "Query Challenge 27", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 28, title: "Query Challenge 28", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 29, title: "Query Challenge 29", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 30, title: "Query Challenge 30", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 31, title: "Query Challenge 31", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 32, title: "Query Challenge 32", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 33, title: "Query Challenge 33", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 34, title: "Query Challenge 34", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 35, title: "Query Challenge 35", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 36, title: "Query Challenge 36", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 37, title: "Query Challenge 37", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 38, title: "Query Challenge 38", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 39, title: "Query Challenge 39", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 40, title: "Query Challenge 40", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 41, title: "Query Challenge 41", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 42, title: "Query Challenge 42", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 43, title: "Query Challenge 43", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 44, title: "Query Challenge 44", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 45, title: "Query Challenge 45", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 46, title: "Query Challenge 46", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 47, title: "Query Challenge 47", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
    { id: 48, title: "Query Challenge 48", tags: ["SELECT", "WHERE"], difficulty: "Easy" },
    { id: 49, title: "Query Challenge 49", tags: ["SELECT", "WHERE"], difficulty: "Medium" },
    { id: 50, title: "Query Challenge 50", tags: ["SELECT", "WHERE"], difficulty: "Hard" },
]
